travis:
  secure:
    BINSTAR_TOKEN: RDajISSOEmsvPj5wXTGA0y+2K6LvyTNwH/rDv7ELVXSdxXpUY3tKem3PScyabkDh3iXrRi3ItBPKqeyz8OFa5D6HVszt3UgehGjkU1S+4TNQ7oOyy/YAgLIeYG9t1F9iknpyZSWUQh+IfFH9ITLWPHhj7LMH2Uslc7hIgDBOp3UKAYpydFEz/si7BoGG5UByormcVSPUNT6oKNwesXAj6lqoc8E0ghSm+iqCFMO+CcDtzlPK3DT0H9eYCrvBS1yc7UqPpH0XA48b7B//vY2KUFQHkjvd4fVHeMSEQP9KHpj2IhH9woh7ovt7g2sFY5sWnFm/6xkOhbtC9dB5lZnsrk9DMCiLCtPGDEZA5JuDh4pUvMGBJcDEUZQfqwKfahBuyIPrcfoXMFwHkUHvLU5cAXK0KGC0M0kRxKzzFobYZEvEEbP2QS6mGzi6ERb3YbEYnt+qlTLjqArv0RtNhdQce7ypvmGBqr8assMGm2Rs/PTpMt4sLpX8FpQhHUuQ834LTU7Jw2/7yeuedG3cH+MDW4YzrZ9bCx+b1A5J2mryvMrlGaOaTeLTb7VBbitvuzV1uPxnsEjiLpIfEi81Y2lnIJ49WUax+fjttl6NgRUiWklE7AveOdcUvypB3+ViHorFAg/JxE35YOAtLEECJHxyXIcNZpmZDKjeIn96ZYXAy2U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
